Repository thatsrightcat/codeit-12, pull requests merged in 2024-08, with the labels that each got.

#78 Feat: #49 인기체험 및 카테고리 정렬 기능 추가
  package-lock.json
  package.json
  src/app/(app)/page.tsx
  src/app/components/MainPage/ActivityCard.tsx
  src/app/components/MainPage/ActivityCardList.tsx
  src/app/components/MainPage/CategoryFilter.tsx
  src/app/components/MainPage/CategorySort.tsx
  src/app/components/MainPage/PopularActivityCard.tsx
  src/app/components/MainPage/PopularActivityList.tsx
  src/app/components/MainPage/Sort.tsx
Labels: 멘토링

#81 fix: #80 카카오맵 라이브러리 재설치
  package-lock.json
  package.json
  src/app/components/ActivityDetailPage/ActivityImageSlider.tsx
Labels: 개선사항

#82 Fix: #49 slick 라이브러리 오류 수정
  src/app/components/MainPage/ActivityCard.tsx
  src/app/components/MainPage/CategorySort.tsx
  src/app/components/MainPage/PopularActivityCard.tsx
  src/app/components/MainPage/PopularActivityList.tsx
Labels: 멘토링

#79 76 feat calendar input 컴포넌트 개발
  package-lock.json
  package.json
  src/app/(app)/mypage/activity-status/CalendarSection.tsx
  src/app/(app)/mypage/layout.tsx
  src/app/(app)/mypage/me/page.tsx
  src/app/(auth)/inputtest/page.tsx
  src/app/components/Form/TestForm.tsx
  src/app/components/Input/CalendarInput.tsx
  src/app/components/Input/DropDownInput.tsx
  src/types/Auth.ts
Labels: 특정기능

#83 feat: 등록된 내용이 없을 때 컴포넌트 제작
  src/app/(app)/mypage/activity-list/page.tsx
  src/app/components/EmptyState/EmptyState.tsx
Labels: 특정기능

#87 Feat: #49 메인페이지 검색 기능 구현 - 여러가지 수정 필요
  src/app/(app)/layout.tsx
  src/app/(app)/mypage/activity-status/CalendarSection.tsx
  src/app/(app)/mypage/layout.tsx
  src/app/(app)/page.tsx
  src/app/components/MainPage/ActivityCard.tsx
  src/app/components/MainPage/ActivityCardList.tsx
  src/app/components/MainPage/PopularActivityCard.tsx
  src/app/components/MainPage/PopularActivityList.tsx
  src/app/components/MainPage/SearchActivityResult.tsx
  src/app/layout.tsx
Labels: 멘토링

#86 Feat: 예약현황 페이지 1차완성 & 드롭다운인풋 리팩토링 & 토큰 재발급 로직 수정
  package-lock.json
  package.json
  public/images/image_loading.gif
  public/images/loading_text.gif
  public/images/no_notification2.gif
  src/api/MyActivity-Status.ts
  src/api/MyActivityStatusApi.ts
  src/api/axios.ts
  src/app/(app)/mypage/activity-list/MyActivity.tsx
  src/app/(app)/mypage/activity-list/page.tsx
  src/app/(app)/mypage/activity-status/Calendar.css
  src/app/(app)/mypage/activity-status/CalendarSection.tsx
  src/app/(app)/mypage/activity-status/components/CalendarSection.tsx
  src/app/(app)/mypage/activity-status/components/DropDownSection.tsx
  src/app/(app)/mypage/activity-status/components/NextMonthIcon.tsx
  src/app/(app)/mypage/activity-status/components/PopUpMenu.tsx
  src/app/(app)/mypage/activity-status/components/PrevMonthIcon.tsx
  src/app/(app)/mypage/activity-status/components/ReservationStatusBadge.tsx
  src/app/(app)/mypage/activity-status/components/ReservationStatusBar.tsx
  src/app/(app)/mypage/activity-status/components/ScheduleReservationsCardList.tsx
  src/app/(app)/mypage/activity-status/page.tsx
  src/app/(app)/mypage/layout.tsx
  src/app/(app)/mypage/reservations/page.tsx
  src/app/(auth)/inputtest/page.tsx
  src/app/components/Form/TestForm.tsx
  src/app/components/Input/DropDownInput.tsx
  src/app/components/Loading/MypageLoading.tsx
  src/context/AuthContext.tsx
  src/context/MyActivityListContext.tsx
  src/hooks/useDailyReservations.ts
  src/hooks/useMonthlyReservations.ts
  src/hooks/useScheduleReservations.ts
  src/hooks/useUpdateReservationStatus.ts
  src/lib/Calendar/MyActivityStatusCalendar.css
  src/types/MyActivity-Status.ts
  src/types/MyActivityStatusType.ts
Labels: 멘토링

#94 Refactor: #84 슬라이더 및 반응형
  package-lock.json
  package.json
  public/icons/icon_detail_arrow_next.svg
  public/icons/icon_detail_arrow_prev.svg
  src/app/(app)/activities/[activityId]/loading.tsx
  src/app/(app)/activities/[activityId]/page.tsx
  src/app/components/ActivityDetailPage/ActivityDetailReviews.tsx
  src/app/components/ActivityDetailPage/ActivityHeader.tsx
  src/app/components/ActivityDetailPage/ActivityIconWrap.tsx
  src/app/components/ActivityDetailPage/ActivityImageSlider.tsx
  src/app/components/ActivityDetailPage/ReservationCard.tsx
  src/app/components/ActivityDetailPage/ReservationCardDesktop.tsx
  src/app/components/ActivityDetailPage/ReservationCardMobile.tsx
  src/app/components/ActivityDetailPage/ReviewCard.tsx
  src/app/components/ActivityDetailPage/slick.css
  src/types/ActivityDetailTypes.ts
  tailwind.config.ts
Labels: 개선사항

#93 46 feat 내 체험 등록 제작
  src/api/activities.ts
  src/api/myActivites.ts
  src/app/(app)/mypage/activity-list/Editor.tsx
  src/app/(app)/mypage/activity-list/MyActivity.tsx
  src/app/(app)/mypage/activity-list/[activityId]/edit/page.tsx
  src/app/(app)/mypage/activity-list/create/page.tsx
  src/app/(app)/mypage/activity-list/page.tsx
  src/app/components/Input/BasicInput.tsx
  src/app/components/Input/CalendarInput.tsx
  src/app/components/SideNavigation/NavItem.tsx
  src/app/globals.css
  src/context/MyActivityListContext.tsx
Labels: 미완성, 멘토링

#97 Feat: #88 알림창 제작 - 보완 필요
  src/app/components/Header/NotificationMenu.tsx
  src/app/components/MainPage/CategorySort.tsx
  src/app/components/Notification/NotificationCard.tsx
  src/app/components/Notification/Notifications.tsx
  src/hooks/useUpdatedAt.tsx
  src/types/Notification.ts
Labels: 멘토링

#100 Refactor: CalendarInput & DropDownInput 외부 클릭시 닫히도록 Refactoring 및 예약승인, 거절버튼 클릭시 useMutation 사용하도록 개선
  src/app/(app)/mypage/activity-status/components/CalendarSection.tsx
  src/app/(app)/mypage/activity-status/components/ScheduleReservationsCardList.tsx
  src/app/components/Input/CalendarInput.tsx
  src/app/components/Input/DropDownInput.tsx
Labels: 개선사항

#105 Feat: #103 예약 내역 페이지 구현 사항
  public/icons/icon_check.svg
  src/api/myReservation.ts
  src/app/(app)/mypage/reservations/components/MyReservationCard.tsx
  src/app/(app)/mypage/reservations/components/ReservationCancelModal.tsx
  src/app/(app)/mypage/reservations/page.tsx
Labels: 멘토링

#108 Feat: #103 예약 내역 페이지 필터 기능 구현
  src/app/(app)/mypage/reservations/components/ReservationFilter.tsx
  src/app/(app)/mypage/reservations/page.tsx
  src/app/components/MainPage/ActivityCardList.tsx
Labels: 멘토링

#99 feat: 예약하기 기능, 자기 체험 수정, 삭제 기능
  src/api/fetchActivityDetail.ts
  src/app/(app)/activities/[activityId]/loading.tsx
  src/app/(app)/activities/[activityId]/page.tsx
  src/app/components/ActivityDetailPage/ActivityDetailReviews.tsx
  src/app/components/ActivityDetailPage/ActivityHeader.tsx
  src/app/components/ActivityDetailPage/ActivityHeaderKebabMenu.tsx
  src/app/components/ActivityDetailPage/ActivityIconWrap.tsx
  src/app/components/ActivityDetailPage/ActivityImageSlider.tsx
  src/app/components/ActivityDetailPage/ActivityKakaoMap.tsx
  src/app/components/ActivityDetailPage/ReservationCard.tsx
  src/app/components/ActivityDetailPage/ReservationCardDesktop.tsx
  src/app/components/ActivityDetailPage/customCalendar.css
  src/hooks/useDetailSchedulesReservations.ts
Labels: 도움, 멘토링

#110 Feat: 리뷰 모달 완성
  src/app/(app)/mypage/activity-status/page.tsx
  src/app/(app)/mypage/reservations/components/MyReservationCard.tsx
  src/app/(app)/mypage/reservations/components/ReservationReviewModal.tsx
  src/app/(app)/mypage/reservations/page.tsx
  src/app/components/Input/BasicInput.tsx
  src/app/components/Modal/Modal.tsx
  src/hooks/useDropdown.ts
Labels: 멘토링

#115 Refactor: #109 메인페이지 리팩토링
  src/app/(app)/page.tsx
  src/app/components/MainPage/ActivityCard.tsx
  src/app/components/MainPage/ActivityCardList.tsx
  src/app/components/MainPage/Pagination.tsx
  src/app/components/MainPage/PopularActivityCard.tsx
  src/app/components/MainPage/PopularActivityList.tsx
  src/app/components/MainPage/Slider.css
Labels: 개선사항

#116 Refactor: #113 예약 내역 페이지 리팩토링
  src/api/myReservation.ts
  src/app/(app)/mypage/reservations/components/MyReservationCard.tsx
  src/app/(app)/mypage/reservations/page.tsx
Labels: 개선사항

#120 96 feat 예약카드 카카오맵 기능
  .gitignore
  process.env
  src/api/fetchActivityDetail.ts
  src/app/(app)/activities/[activityId]/page.tsx
  src/app/apiServer/axiosServer.tsx
  src/app/apiServer/getUserMeServer.ts
  src/app/components/ActivityDetailPage/ActivityHeader.tsx
  src/app/components/ActivityDetailPage/ActivityImageSlider.tsx
  src/app/components/ActivityDetailPage/ReservationCard.tsx
  src/app/components/ActivityDetailPage/ReservationCardDesktop.tsx
Labels: 개선사항

#125 121 refactor 예약카드 기능 완성
  .gitignore
  package-lock.json
  package.json
  process.env
  src/api/fetchActivityDetail.ts
  src/app/(app)/activities/[activityId]/loading.tsx
  src/app/(app)/activities/[activityId]/page.tsx
  src/app/components/ActivityDetailPage/ActivityHeader.tsx
  src/app/components/ActivityDetailPage/ActivityImageSlider.tsx
  src/app/components/ActivityDetailPage/ActivityKakaoMap.tsx
  src/app/components/ActivityDetailPage/ReservationCard.tsx
  src/app/components/ActivityDetailPage/ReservationCardDesktop.tsx
  src/app/components/ActivityDetailPage/ReservationCardStateTest.tsx
  src/app/components/ActivityDetailPage/customCalendar.css
  src/hooks/useKakaoLoader.tsx
Labels: 특정기능, 개선사항

#127 Refactor: 내정보 페이지 basicInput 타입 password로 변경
  src/app/(app)/mypage/me/component/MyInfoEditor.tsx
Labels: 개선사항

#133 fix: 예약카드 중복 신청 수정
  src/app/components/ActivityDetailPage/ReservationCardDesktop.tsx
Labels: 버그, 개선사항

#139 Refactor: 예약카드 반응형 스타일 및 카카오맵키 환경변수 설정
  .gitignore
  src/app/(app)/activities/[activityId]/page.tsx
  src/app/components/ActivityDetailPage/ReservationCardDesktop.tsx
  src/app/components/ActivityDetailPage/ReservationCardMobile.tsx
  src/app/components/ActivityDetailPage/ReservationCardMobileOpener.tsx
  src/hooks/useKakaoLoader.tsx
Labels: 개선사항

#144 feat: 카카오맵 배포용 키 등록
  .gitignore
  src/app/components/ActivityDetailPage/ActivityHeaderKebabMenu.tsx
  src/app/components/ActivityDetailPage/ReservationCardDesktop.tsx
Labels: 특정기능

#150 Refactor: 삭제 모달 정렬, useQuery staleTime 5분, 예약카드 테블릿 버전 예약카드 모달 z-inde…
  .env
  src/app/(app)/activities/[activityId]/page.tsx
  src/app/components/ActivityDetailPage/ActivityHeaderKebabMenu.tsx
  src/app/components/ActivityDetailPage/ActivityImageSlider.tsx
  src/app/components/ActivityDetailPage/ReservationCard.tsx
  src/app/components/ActivityDetailPage/ReservationCardDesktop.tsx
  src/app/components/ActivityDetailPage/ReservationCardMobile.tsx
  src/app/components/ActivityDetailPage/ReservationCardMobileOpener.tsx
  src/app/components/ActivityDetailPage/slick.css
Labels: 개선사항

#155 Refactor: #149 url 쿼리 스트링 수정
  src/app/components/ActivityDetailPage/ActivityDetailReviews.tsx
  src/app/components/MainPage/ActivityCardList.tsx
  src/app/components/MainPage/Pagination.tsx
Labels: 개선사항
